#!/usr/bin/env node
// Postinstall script to create default.js for Prisma client
// This avoids circular dependency issues

const fs = require('fs');
const path = require('path');

const prismaClientPath = path.resolve(__dirname, '../node_modules/@prisma/client');
const defaultJsPath = path.join(prismaClientPath, '.prisma/client/default.js');
const generatedClientPath = path.resolve(__dirname, '../node_modules/.prisma/client');

// Ensure directory exists
const defaultJsDir = path.dirname(defaultJsPath);
if (!fs.existsSync(defaultJsDir)) {
  fs.mkdirSync(defaultJsDir, { recursive: true });
}

// Create default.js that exports PrismaClient from the generated client
// We use a lazy getter to avoid circular dependency at module load time
const defaultJsContent = `// Prisma Client Default Export
// Generated by postinstall script
// Exports PrismaClient from the generated client location

const path = require('path');
const generatedPath = path.resolve(__dirname, '../../../.prisma/client');

// Use a lazy getter to break circular dependency
let _PrismaClient = null;

function getPrismaClient() {
  if (!_PrismaClient) {
    // Access @prisma/client which will resolve correctly
    // The circular dependency warning is expected but won't break functionality
    const prismaModule = require('@prisma/client');
    _PrismaClient = prismaModule.PrismaClient || prismaModule.default?.PrismaClient || prismaModule;
  }
  return _PrismaClient;
}

module.exports = {
  get PrismaClient() {
    return getPrismaClient();
  }
};
`;

fs.writeFileSync(defaultJsPath, defaultJsContent, 'utf8');
console.log('✅ Created Prisma client default.js file');

